### ISSUE TITLE
Have two columns in the pull down menus (Home Page)

### ISSUE THREAD

**Issue by PadawanTony** [Hub-IT/itpedia#18]
Can we have the pull down menus appear in two columns (one opposing the other) in the home page?

The client wants them like this on a desktop, but on mobiles they should appear in one column like we have them now.

But do you think that this will confuse the users as to the order in which they have to fill the menus?
(I think yes despite having them disabled).

**Comment by rdok** [comment]
Yes, it may confuse users. Although there not many users that will go to both desktop and mobile to check, and it is supported extensively by the Bootstrap Framework--[source](http://getbootstrap.com/css/#grid).

**Comment by rdok** [comment]
[See](http://getbootstrap.com/css/#grid-media-queries) for bootstrap sizes.

**Comment by PadawanTony** [comment]
Man the columns are not aligned correctly. See the word "Industry".

And also the submit button is on the right. And it seems awful. 

Maybe put it in the middle?

(Still I don't like this approach but I guess we have to wait and see)

**Comment by PadawanTony** [comment]
I reverted back to one column display but the deployement in app-harbor failed for some reason.

Fix it?
