### ISSUE TITLE
RSS Icon

### ISSUE THREAD

**Issue by PadawanTony** [Hub-IT/itpedia#20]
Put a little icon next to the RSS word in Dictionary.

And also fix the styling a bit

**Comment by PadawanTony** [comment]
Doesn't show in the production server!

**Comment by PadawanTony** [comment]
The icon is not displayed in the production server!

**Comment by rdok** [comment]
@PadawanTony Whenever you add assets to the Visual studio, you need to explicitly tell it to include into the project. When the appharbor recieved the code, it was not including the rss image you had included. In any case, [fontawesome](http://fortawesome.github.io/Font-Awesome/icon/rss-square/) is a much better solution.

**Comment by PadawanTony** [comment]
Yes I imagined that was the issue. How do you tell visual studio to include it?

**Comment by rdok** [comment]
[Same thing with files.](http://stackoverflow.com/a/392477/2790481)

**Comment by PadawanTony** [comment]
I see. But why do we have to do this? From the moment i put it in the project, doesn't it mean that I want it there? I mean, why would I want to have it there but not include it?

**Comment by rdok** [comment]
Was not interested to learn enough to learn why--Visual studio has too much low performance for me to learn the in's and out--I prefer to spend my time building the actual app, rather than fixing it's errors. JetBrains on the other hand ;)
