### ISSUE TITLE
Fix footer responsive design.

### ISSUE THREAD

**Issue by rdok** [Hub-IT/itpedia#24]
@PadawanTony  
- Please use bootstrap [grid](https://getbootstrap.com/examples/grid/) instead of the current [custom one](https://github.com/Hub-IT/itpedia/blob/master/ITPedia/Content/Site.css#L82). Doing so, the bootstrap framework will detect, and if possible align each logo to look even better.   
- The copyright text is partially obstructed. 
- There is a white gap.  

![footer_bug](https://cloud.githubusercontent.com/assets/4212119/12835116/f41e3ac2-cbb5-11e5-8f64-0b7343b64d47.jpg)

**Comment by PadawanTony** [comment]
I fixed this

**Comment by rdok** [comment]
@PadawanTony  
- Please use bootstrap [grid](https://getbootstrap.com/examples/grid/) instead of the current [custom one](https://github.com/Hub-IT/itpedia/blob/master/ITPedia/Content/Site.css#L82). Doing so, the bootstrap framework will detect, and if possible align each logo to look even better.   
- The copyright text is partially obstructed. 
- There is a white gap.

**Comment by PadawanTony** [comment]
You are right. I'm finished for tonight. You do whatever you want.

Good night!
