### ISSUE TITLE
Add results categories.

### ISSUE THREAD

**Issue by rdok** [Hub-IT/itpedia#25]
>At the results page, please add another "box" (probably under "Applications" saying:

>**Fixed costs**
>Installation
>Parameterization
>User training

>**Recurring costs**
>Hosting fees
>Software licenses
>Maintenance

**Comment by PadawanTony** [comment]
Could we somehow differentiate between these two and the previous ones?

Maybe by having a small line separating them? Or sth else.

**Comment by PadawanTony** [comment]
Good job
